import Foundation

extension LocalizationCatalog {
    static let screenTable: [String: (en: String, zh: String)] = [
        "tab.dashboard": ("Home", "首页"),
        "tab.today": ("Today", "今日"),
        "tab.exercises": ("Exercises", "动作"),
        "tab.profile": ("Profile", "档案"),
        "tab.history": ("History", "历史"),
        "tab.settings": ("Settings", "设置"),

        "dashboard.title": ("Health Planner", "健康训练计划"),
        "dashboard.subtitle": ("Daily adaptive training guidance", "每日自适应训练建议"),
        "dashboard.readiness": ("Today's Status", "今日状态"),
        "dashboard.statusWithScore": ("Status %d", "状态 %d"),
        "dashboard.status": ("System Status", "系统状态"),
        "dashboard.metrics": ("Current vs Baseline", "当前值与基线"),
        "dashboard.recovery": ("Recovery State", "恢复状态"),
        "dashboard.why": ("Why This Recommendation", "推荐原因"),
        "dashboard.debug": ("Debug", "调试"),
        "dashboard.stepTarget": ("of expected steps", "达到当前时段目标"),
        "dashboard.routine": ("Routine Recommendation", "作息推荐"),
        "dashboard.bedtime": ("Bedtime target %02d:%02d", "建议入睡 %02d:%02d"),

        "label.sleep": ("Sleep", "睡眠"),
        "label.restingHR": ("Resting HR", "静息心率"),
        "label.hrv": ("HRV", "心率变异性"),
        "label.steps": ("Steps", "步数"),
        "label.expectedNow": ("Expected now", "当前时段目标"),
        "label.current": ("Current", "当前"),
        "label.recentAverage": ("Recent average", "近期均值"),
        "label.weekAverage": ("7-day average", "7日均值"),
        "label.target": ("Target", "目标"),
        "label.baseline": ("Baseline", "基线"),
        "label.deviation": ("Deviation", "偏差"),
        "label.ahead": ("Ahead", "领先"),
        "label.behind": ("Behind", "落后"),
        "label.todayLow": ("Today's Low", "今日最低"),
        "label.todayHigh": ("Today's High", "今日最高"),
        "label.systemic": ("Systemic load", "全身负荷"),
        "label.passiveScore": ("Passive score", "被动恢复分"),
        "label.lastLoad": ("Last load", "上次加载"),
        "label.lastError": ("Last error", "上次错误"),
        "label.metricsLoaded": ("Metrics loaded", "指标已加载"),
        "label.enabledExercises": ("Enabled exercises", "已启用动作"),
        "label.scoreDrivers": ("Score drivers", "评分驱动"),
        "label.recScores": ("Recommendation scores", "推荐评分"),
        "label.confidence": ("Confidence", "置信度"),
        "label.safety": ("Safety", "安全"),
        "label.startedAt": ("Session started", "训练开始于"),
        "label.score": ("Score", "评分"),
        "label.intensity": ("Intensity", "强度"),
        "label.planned": ("Planned", "计划"),
        "label.completed": ("Completed", "完成"),
        "label.front": ("Front", "前侧"),
        "label.back": ("Back", "后侧"),
        "label.arms": ("Arms", "手臂"),
        "label.cardio": ("Cardio", "有氧"),
        "label.strength": ("Strength", "力量"),
        "label.mobility": ("Mobility", "灵活性"),
        "label.windows": ("7/28/84 windows", "7/28/84 时间窗"),
        "label.status": ("Status", "状态"),
        "label.recommendation": ("Recommendation", "建议"),

        "button.refresh": ("Refresh", "刷新"),
        "button.requestHealth": ("Request Health Access", "请求健康权限"),
        "button.startSession": ("Start Session", "开始训练"),
        "button.endSession": ("End Session", "结束训练"),
        "button.save": ("Save", "保存"),
        "button.saveProfile": ("Save Profile", "保存档案"),
        "button.add": ("Add", "添加"),
        "button.saveNote": ("Save Note", "保存备注"),
        "button.done": ("Done", "完成"),

        "today.prescription": ("Today's Prescription", "今日训练建议"),
        "today.statusCard": ("Today's Status", "今日状态"),
        "today.plan": ("Session Plan", "训练计划"),
        "today.lowFriction": ("Session Status", "训练状态"),
        "today.sessionStatus": ("Session Status", "训练状态"),
        "today.optionalFeedback": ("Optional Manual Feedback", "可选手动反馈"),
        "today.noSpecific": ("No specific exercises today", "今天无需指定动作"),
        "today.elapsed": ("Elapsed", "已进行"),
        "today.completed": ("Completed today", "今日已完成"),
        "today.doneTitle": ("Today's plan completed", "今日计划已完成"),
        "today.completedCard": ("Completed", "已完成"),
        "today.encouragement": ("Good work. Let the rest of the day stay easy and recovery-oriented.", "完成得不错。今天余下时间以轻松恢复为主。"),
        "today.completedSummary": ("Training is complete. Keep the rest of the day recovery-oriented.", "训练已完成，今天余下时间以恢复为主。"),
        "today.inProgress": ("Session in progress", "训练进行中"),
        "today.inProgressSummary": ("Finish the planned work, then switch to easy recovery for the rest of the day.", "完成本次计划后，余下时间转为轻松恢复。"),
        "today.recoveryAdvice": ("For the rest of today, prioritize hydration, light movement, and sleep.", "今天余下时间优先补水、轻活动和睡眠。"),
        "today.tomorrowRecovery": ("Tomorrow will likely stay recovery-focused.", "明天大概率仍以恢复为主。"),
        "today.tomorrowLighter": ("Tomorrow will likely shift lighter than today.", "明天大概率会比今天更轻。"),
        "today.tomorrowBalanced": ("Tomorrow will likely remain balanced if recovery stays stable.", "如果恢复稳定，明天大概率保持均衡安排。"),
        "plan.mobilityFlowGuidance": ("Gentle range-of-motion sequence", "轻柔活动关节与活动度恢复"),
        "plan.load.bodyweightAdded": ("Bodyweight or small added load, RIR 2-3", "自重或小幅加重，保留 2-3 次余力"),
        "plan.load.assistedBodyweight": ("Assisted or bodyweight reps, RIR 2-3", "辅助或自重完成，保留 2-3 次余力"),
        "plan.load.moderateTempo": ("Moderate load, controlled tempo, RIR 2-3", "中等负重，控制节奏，保留 2-3 次余力"),
        "plan.load.rpe67": ("RPE 6-7, leave 3 reps in reserve", "主观强度 6-7，保留 3 次余力"),
        "plan.load.rpe68": ("RPE 6-8, leave 2-3 reps in reserve", "主观强度 6-8，保留 2-3 次余力"),

        "profile.basic": ("Basic", "基础信息"),
        "profile.goal": ("Goal & Level", "目标与经验"),
        "profile.self": ("Self Assessment", "自我评估"),
        "profile.savedAt": ("Last saved", "上次保存"),
        "profile.complete": ("Profile completeness", "档案完整度"),
        "profile.completeYes": ("Sufficient for recommendations", "可用于推荐"),
        "profile.completeNo": ("Needs basic body metrics", "需补充基础体征"),
        "profile.saveSuccess": ("Profile saved successfully", "档案保存成功"),
        "profile.saveFailed": ("Please check required fields", "请检查必填字段"),

        "field.height": ("Height (cm)", "身高 (cm)"),
        "field.weight": ("Weight (kg)", "体重 (kg)"),
        "field.age": ("Age (optional)", "年龄（可选）"),
        "field.sex": ("Sex", "性别"),
        "field.goal": ("Goal", "目标"),
        "field.experience": ("Experience", "经验"),
        "field.gym": ("Gym access", "有健身房条件"),
        "field.equipmentNotes": ("Equipment notes", "器械备注"),
        "field.5k": ("Estimated 5k (min)", "5公里预计时间(分钟)"),
        "field.pushups": ("Max push-ups", "最大俯卧撑"),
        "field.pullups": ("Max pull-ups", "最大引体向上"),
        "field.bench": ("Bench max est (kg)", "卧推估计最大(kg)"),
        "field.lat": ("Lat pulldown max est (kg)", "高位下拉估计最大(kg)"),
        "field.squat": ("Squat max est (kg)", "深蹲估计最大(kg)"),

        "exercise.enable": ("Enable Allowed Exercises", "启用可做动作"),
        "exercise.custom": ("Add Custom Exercise", "添加自定义动作"),
        "exercise.name": ("Exercise name", "动作名称"),
        "exercise.category": ("Category", "类别"),
        "exercise.equipment": ("Equipment", "器械"),
        "exercise.primary": ("Primary muscle", "主肌群"),

        "history.passive": ("Passive Recovery Responses", "被动恢复反馈"),
        "history.sessions": ("Workout Sessions", "训练记录"),

        "settings.health": ("Health Data", "健康数据"),
        "settings.notifications": ("Notifications", "通知"),
        "settings.language": ("Language", "语言"),
        "settings.debug": ("Show debug info", "显示调试信息"),
        "settings.enableReminder": ("Enable local reminders", "开启本地提醒"),
        "settings.requestNotification": ("Request Notification Permission", "请求通知权限"),
        "settings.jumpProfile": ("Go to Profile", "前往档案页"),
        "settings.jumpExercise": ("Go to Exercise Selection", "前往动作选择"),
        "settings.reloadNow": ("Refresh Data Now", "立即刷新数据"),
        "settings.reset": ("Reset Local Data", "重置本地数据"),
        "settings.resetConfirm": ("Delete all local app data?", "删除所有本地数据？"),
        "settings.cancel": ("Cancel", "取消"),
        "settings.confirm": ("Confirm", "确认"),

        "feedback.hint": ("The app primarily uses passive physiological feedback; manual feedback is optional.", "应用优先使用被动生理反馈，手动反馈仅可选。"),
        "feedback.note": ("Optional note", "可选备注"),

        "common.loading": ("Loading...", "加载中..."),
        "common.none": ("None", "无"),
        "common.notLoaded": ("Not loaded yet", "尚未加载"),
        "common.noData": ("No data", "暂无数据"),
        "common.nA": ("N/A", "无"),
        "common.min": ("min", "分钟"),
        "common.rest": ("Rest", "休息"),

        "rec.type.rest": ("Rest", "休息"),
        "rec.type.walk": ("Walk", "步行"),
        "rec.type.easyRun": ("Easy Run", "轻松跑"),
        "rec.type.strength": ("Strength", "力量"),
        "rec.type.mobility": ("Mobility", "灵活性"),
        "rec.headline.walk": ("Walk", "散步"),
        "rec.headline.run": ("Run", "跑步"),
        "rec.headline.mobility": ("Recovery Activity", "恢复活动"),
        "rec.headline.recovery": ("Recovery First", "优先恢复"),
        "rec.headline.back": ("Back Session", "背部训练"),
        "rec.headline.chest": ("Chest Session", "胸部训练"),
        "rec.headline.lower": ("Lower Body Session", "下肢训练"),

        "rec.intensity.low": ("Low", "低"),
        "rec.intensity.moderate": ("Moderate", "中"),
        "rec.intensity.high": ("High", "高"),

        "rec.volume.light": ("Light", "轻量"),
        "rec.volume.moderate": ("Moderate", "中量"),
        "rec.volume.hard": ("Hard", "高量"),

        "rec.todayPrefix": ("Today", "今日"),
        "rec.detailFormat": ("%@ min • %@ • %@", "%@ 分钟 • %@ • %@"),
        "rec.explanationFormat": ("Recovery %@, activation %@, passive %@, focus: %@.", "恢复 %@，激活 %@，被动反馈 %@，重点：%@。"),

        "status.unknown": ("Authorization state unknown", "权限状态未知"),
        "status.request": ("Request available", "可请求权限"),
        "status.ready": ("Configured in Health app / Ready to load data", "已在健康中配置 / 可加载数据"),
        "status.failed": ("Load failed", "加载失败"),

        "fallback.noSamples": ("No samples returned", "未返回样本"),
        "fallback.noRecent": ("Permission may be configured but this metric has no recent entries", "可能已授权，但近期无数据"),
        "fallback.queryFailed": ("Query failed", "查询失败"),
        "fallback.safetyStress": ("Physiological stress appears elevated today. Prefer recovery activity.", "今日生理压力偏高，建议恢复活动。"),
        "common.rpe": ("RPE 6-8", "主观强度 6-8"),

        "muscle.chest": ("chest", "胸部"),
        "muscle.back": ("back", "背部"),
        "muscle.biceps": ("biceps", "肱二头"),
        "muscle.forearms": ("forearms", "前臂"),
        "muscle.quads": ("quads", "股四头"),
        "muscle.hamstrings": ("hamstrings", "腘绳肌"),
        "muscle.glutes": ("glutes", "臀部"),
        "muscle.adductors": ("adductors", "内收肌"),
        "muscle.calves": ("calves", "小腿"),
        "muscle.cardioSystemic": ("cardio/systemic", "心肺/全身"),

        "recovery.fresh": ("Fresh", "状态新鲜"),
        "recovery.recovering": ("Recovering", "恢复中"),
        "recovery.fatigued": ("Fatigued", "疲劳"),
        "todayStatus.high": ("High and steady", "状态充足"),
        "todayStatus.stable": ("Stable", "状态平稳"),
        "todayStatus.dipping": ("Starting to drop", "状态开始下降"),
        "todayStatus.low": ("Needs recovery", "状态偏低"),
        "todayStatus.reason.daylight": ("Being awake longer through the day is naturally lowering your status.", "随着白天清醒时间变长，状态会自然下降。"),
        "todayStatus.reason.training": ("Today's completed training is still pulling status down.", "今天已完成的训练仍在拉低当前状态。"),
        "todayStatus.reason.systemic": ("Systemic fatigue is still elevated right now.", "当前全身疲劳仍然偏高。"),
        "todayStatus.reason.morning": ("Morning recovery signals are still supporting today's status.", "晨间恢复信号仍在支撑今天的状态。"),
        "todayStatus.reason.ready": ("Current body-state still supports normal training load.", "当前身体状态仍支持常规训练负荷。"),
        "todayStatus.reason.keepEasy": ("Keep the rest of today on the easy side.", "今天余下时间建议偏轻松。"),

        "hrv.status.high": ("Recovered well", "恢复较好"),
        "hrv.status.stable": ("Within normal range", "处于正常范围"),
        "hrv.status.low": ("Below baseline", "低于个人基线"),
        "hrv.status.missing": ("Need more HRV history", "需要更多 HRV 历史"),
        "hrv.meaning.high": ("Autonomic recovery looks favorable today.", "今天的自主神经恢复信号较好。"),
        "hrv.meaning.stable": ("Recovery signal is broadly stable versus your usual range.", "恢复信号与平时大致稳定。"),
        "hrv.meaning.low": ("Recovery may be under pressure. Keep today's load conservative.", "恢复可能承压，今天建议更保守。"),
        "hrv.meaning.missing": ("Once more recent HRV data is available, the app will classify today's status.", "获得更多近期 HRV 数据后，应用会给出更明确判断。"),
        "rhr.status.low": ("Calm", "状态平稳"),
        "rhr.status.stable": ("Near your baseline", "接近个人基线"),
        "rhr.status.high": ("Elevated", "偏高"),
        "rhr.status.missing": ("Need more resting HR history", "需要更多静息心率历史"),
        "rhr.meaning.low": ("Resting load looks light today.", "今天静息负荷较轻。"),
        "rhr.meaning.stable": ("Resting heart rate is close to your usual range.", "静息心率接近平时范围。"),
        "rhr.meaning.high": ("Resting load may be elevated. Keep today's effort controlled.", "静息负荷可能偏高，今天强度建议收着一些。"),
        "rhr.meaning.missing": ("Once more recent resting HR data is available, the app will classify today's status.", "获得更多近期静息心率数据后，应用会给出更明确判断。"),
        "rhr.analysis.low": ("Today's resting heart rate is lower than your usual range. This often matches better recovery, lighter stress, or a calmer morning. If sleep and HRV also look stable, moderate to stronger training can be considered.", "今天静息心率低于你的常态，常见于恢复较好、压力较轻或早晨状态更平稳。如果睡眠和 HRV 也稳定，可考虑中等到较强训练。"),
        "rhr.analysis.stable": ("Today's resting heart rate is near your usual range. Body load looks broadly normal. Moderate exercise is usually reasonable; if you still feel heavy, keep it easy.", "今天静息心率接近个人常态，身体负荷整体正常。通常可以进行中等强度运动；如果主观感觉疲惫，仍建议以轻松活动为主。"),
        "rhr.analysis.high": ("Today's resting heart rate is above your usual range. Common reasons include poor sleep, accumulated training load, dehydration, illness, or psychological stress. Avoid strong exercise today and prefer walking, mobility, or other gentle movement.", "今天静息心率高于个人常态。常见原因包括睡眠不足、训练负荷累积、脱水、身体不适或心理压力。今天不建议强烈运动，更适合散步、拉伸或其他缓和活动。"),
        "rhr.analysis.missing": ("The app needs more recent resting heart rate data before it can judge today's state.", "应用需要更多近期静息心率数据后，才能更准确判断今天状态。"),
        "hrv.analysis.high": ("Today's HRV is above your usual range. This often matches stronger recovery capacity and lower stress. If resting heart rate is not elevated and you feel okay, moderate to stronger training is usually more acceptable.", "今天 HRV 高于个人常态，常见于恢复能力较好、压力较低的状态。如果静息心率没有升高且自我感觉正常，通常更适合中等到较强训练。"),
        "hrv.analysis.stable": ("Today's HRV is within your usual range. Recovery looks broadly normal. Moderate exercise is usually fine; if other signals look off, stay conservative.", "今天 HRV 处于个人常态范围内，恢复整体正常。通常可以进行中等强度运动；如果其他指标异常，仍建议保守一些。"),
        "hrv.analysis.low": ("Today's HRV is below your usual range. Common reasons include sleep debt, accumulated load, psychological stress, alcohol, or incomplete recovery. Strong exercise is not ideal today; gentle cardio or recovery activity is safer.", "今天 HRV 低于个人常态。常见原因包括睡眠债、训练负荷累积、心理压力、饮酒或恢复不足。今天不适合强烈运动，更适合缓和有氧或恢复活动。"),
        "hrv.analysis.missing": ("The app needs more recent HRV data before it can judge today's state.", "应用需要更多近期 HRV 数据后，才能更准确判断今天状态。"),

        "routine.rest": ("Prioritize recovery rest", "优先恢复休息"),
        "routine.light": ("Keep activity light tonight", "今晚轻量活动"),
        "routine.normal": ("Normal activity is okay tonight", "今晚可保持常规活动"),
        "routine.reason.sleepLow": ("Sleep below baseline", "睡眠低于个人基线"),
        "routine.reason.rhrHigh": ("Resting HR elevated", "静息心率偏高"),
        "routine.reason.hrvLow": ("HRV below baseline", "HRV 低于基线"),
        "routine.reason.lowActivity": ("Low activity so far", "当前活动量偏低"),
        "routine.reason.recentLoad": ("Recent load still high", "近期训练负荷仍高"),
        "routine.reason.weatherIndoor": ("Weather favors indoor plan", "天气更适合室内安排"),
        "routine.reason.tempExtreme": ("Temperature is extreme", "当前温度较极端"),
        "routine.reason.stable": ("Stable recovery signals", "恢复信号整体稳定"),
        "routine.weather.bad": ("Outdoor conditions are not ideal", "室外条件不理想"),
        "routine.weather.good": ("Outdoor conditions are acceptable", "室外条件可接受")
    ]
}
